package claude

import (
	"bytes"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/charmbracelet/log"
)

var httpClient = &http.Client{Timeout: 30 * time.Second}

const (
	ClientID      = "9d1c250a-e61b-44d9-88ed-5944d1962f5e"
	RedirectURI   = "https://console.anthropic.com/oauth/code/callback"
	TokenEndpoint = "https://console.anthropic.com/v1/oauth/token"
	AuthURL       = "https://claude.ai/oauth/authorize"
	Scopes        = "org:create_api_key user:profile user:inference"
)

// GenerateAuthURL creates an OAuth authorization URL with PKCE challenge.
// Returns the full URL to open in the browser and the PKCE verifier.
// The verifier is also used as the state parameter (matches web app behavior).
func GenerateAuthURL() (authURL, verifier string, err error) {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return "", "", fmt.Errorf("failed to generate random bytes: %w", err)
	}
	verifier = hex.EncodeToString(b)

	h := sha256.Sum256([]byte(verifier))
	challenge := base64.RawURLEncoding.EncodeToString(h[:])

	u, _ := url.Parse(AuthURL)
	q := u.Query()
	q.Set("code", "true")
	q.Set("client_id", ClientID)
	q.Set("response_type", "code")
	q.Set("redirect_uri", RedirectURI)
	q.Set("scope", Scopes)
	q.Set("code_challenge", challenge)
	q.Set("code_challenge_method", "S256")
	q.Set("state", verifier)
	u.RawQuery = q.Encode()

	return u.String(), verifier, nil
}

// TokenResponse represents the OAuth token exchange response from Anthropic.
type TokenResponse struct {
	RefreshToken string `json:"refresh_token"`
	AccessToken  string `json:"access_token"`
}

// ExchangeCode exchanges an authorization code for tokens.
// The code parameter is the full pasted value: "authCode#state".
// The verifier is the PKCE verifier generated by GenerateAuthURL.
// The state portion is validated against the verifier to prevent CSRF.
func ExchangeCode(code, verifier string) (*TokenResponse, error) {
	parts := strings.SplitN(strings.TrimSpace(code), "#", 2)
	authCode := parts[0]
	state := ""
	if len(parts) > 1 {
		state = parts[1]
	}

	if state != verifier {
		return nil, fmt.Errorf("OAuth state mismatch: expected state to match verifier (possible CSRF or stale auth URL)")
	}

	log.Debug("exchanging auth code", "endpoint", TokenEndpoint)

	body := map[string]string{
		"code":          authCode,
		"state":         state,
		"grant_type":    "authorization_code",
		"client_id":     ClientID,
		"redirect_uri":  RedirectURI,
		"code_verifier": verifier,
	}
	jsonBody, err := json.Marshal(body)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	resp, err := httpClient.Post(TokenEndpoint, "application/json", bytes.NewReader(jsonBody))
	if err != nil {
		return nil, fmt.Errorf("token exchange request failed: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response: %w", err)
	}
	log.Debug("token exchange response", "status", resp.StatusCode)

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("token exchange failed (%d): %s", resp.StatusCode, string(respBody))
	}

	var result TokenResponse
	if err := json.Unmarshal(respBody, &result); err != nil {
		return nil, fmt.Errorf("failed to parse token response: %w", err)
	}

	return &result, nil
}
